James|
Room layout changed to make sense
Updated the objective list system
Added Puzzle 4

Error: Microchip count doesnt include last number on last value